name: test nodejs client
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/nodejs-client/**"
  push:
    branches:
      - "main"
    paths:
      - "packages/nodejs-client/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd packages/nodejs-client && yarn
      - run: cd packages/nodejs-client && yarn test
        env:
          CI: true

