name: test hyper utils
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/utils/**"
  push:
    branches:
      - "**"
    paths:
      - "packages/utils/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: cd packages/utils && ./scripts/test.sh
        env:
          CI: true
