name: test crawler port
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/port-crawler/**"
  push:
    branches:
      - "**"
    paths:
      - "packages/port-crawler/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.11.x, 1.13.x, 1.14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: cd packages/port-crawler && ./scripts/test.sh
        env:
          CI: true
