name: test queue port
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/port-queue/**"
  push:
    branches:
      - "main"
    paths:
      - "packages/port-queue/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: cd packages/port-queue && ./scripts/test.sh
        env:
          CI: true
